:sparkles: Insert header
gitovep/gitove pull request #15
Opened 2023-08-10 15:52 UTC by codeing999

## 해결하려는 문제가 무엇인가요?
- 사용자가 선택한 '커밋 종류'를 이모지로 변환
- 변환을 거친 커밋 종류, 커밋 도메인, 커밋 제목, 커밋 바디를 특정 형식으로 합쳐 string으로 return 

## 어떻게 해결했나요?
- 아직 정해지지 않았지만 임시로 json 파일을 만들어 그 파일을 읽어 이모지로 변환하는 함수 구현

## 어떤 부분에 집중하여 리뷰해야 할까요?
- 일단 폴더를 분리하여 작업했고, 임시로 타입을 정의했을 뿐 정해진 건 아닙니다.
- 이모지 타입과 커밋 형식을 결정하면 좋을 것 같습니다.
  - 현재 예 : [type][scope]title (한줄 공백) body

## 관련이슈 및 링크
#13

2023-08-10 18:40 UTC, ninthsun91 requested changes
임시 커밋이고 아마 인지하고 계실거라 생각하지만, 일부 변수명이 emoji라서 혹시나 싶어서 언급하는건데 header가 emoji일 필요는 없습니다. 이건 윤주님이 작성하시는 포맷이 어느정도 자리잡히고나면 제가 후딱 로컬에 디폴트 설정 넣어놓을테니 그때가서 다시 네이밍은 변경해도 될 것 같습니다.

그리고 다음의 세 가지는 수정해서 커밋이 추가되면 좋을 것 같아요.

1. commit scope도 commit type처럼 변환이 이루어져야합니다. 만약 의도적으로 다음번 PR에 추가하시려고 누락하신거라면 괜찮습니다.

2. `insertHeader`에서 바디를 변경하지 마시고, 수정한 타이틀만 내보내는게 재훈님이 다음 작업하시기 편할 것 같아요.

action..ts에서 결과적으로,
```
const newTitle = insertHeader(commitMessage);
commitMessage.set('title', newTitle);
```
같은 형식으로 타이틀만 바꿔주고 재훈님이 다시 `commitMessage` 객체를 받아서 처리하시도록 하는게 좋아보입니다.

3. `tsconfig copy.json` 삭제해주세요~

2023-08-11 02:16 UTC, waveinyu approved these changes
확인했습니다. LGTM👍

2023-08-11 11:38 UTC, codeing999 commented
@ninthsun91 말씀하신 부분들 수정했습니다.

2023-08-11 12:23 UTC, ninthsun91 approved these changes
👍

2023-08-11 16:05 UTC, merged