[feat] read config
gitovep/gitove pull request #38
Opened 2023-08-14 11:12 UTC by yunju2

## 해결하려는 문제가 무엇인가요?

- user 설정파일 읽어오기 및 설정값 반환

## 어떻게 해결했나요?
- 논의해서 정한 config file형식에 맞게 user가 저장한 config file 읽어오도록 했습니다.
- 읽어오는 config file을 전역변수에 넣고 configuration keys를 인자로 받아 설정값들을 리턴하도록 했습니다.

## 어떤 부분에 집중하여 리뷰해야 할까요?

-  config file 전역변수 설정이 옳바른지 dir path 설정한 부분이 괜찮은지 집중해서 봐주시면 감사하겠습니다.

## 관련이슈 및 링크
#12

2023-08-14 11:26 UTC, codeing999 approved these changes

2023-08-14 11:26 UTC, codeing999 commented on src/readConfig/getConfigfile.ts
> +export const getConfigfile = () => {
주석 달아주시면 더 좋을 것 같습니다

2023-08-14 11:35 UTC, ninthsun91 commented on package.json
`fs`, `path`, `url`은 Nodejs 내장 라이브러리인데 따로 설치하신 이유가 있을까요?

2023-08-14 11:37 UTC, ninthsun91 requested changes
`fs`, `path`, `url`은 Nodejs 내장 라이브러리인데 따로 설치하신 이유가 있을까요?

2023-08-16 09:16 UTC, yunju2 commented
주석 추가랑 불필요한 async, 패키지 삭제 완료했습니다.

2023-08-16 10:05 UTC, ninthsun91 approved these changes
수고하셨습니다! 깔끔해졌어요👍

2023-08-16 10:06 UTC, waveinyu approved these changes
고생 많으셨습니다!👍🏻👍🏻

2023-08-16 10:06 UTC, merged